@baseUrl=http://localhost:3000

@resourceName=products

# Products

# @name getAll
GET {{baseUrl}}/{{resourceName}}

###
# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?color=yellow&price_lte=500

###
# @name filterProducts
GET {{baseUrl}}/{{resourceName}}?name_like=practical

###
# @name pagination
GET {{baseUrl}}/{{resourceName}}?_page=1&_limit=2

###
# @name sort
GET {{baseUrl}}/{{resourceName}}?_sort=price&_order=desc

###
# @name relationship
GET {{baseUrl}}/{{resourceName}}/chTisEs?_expand=category

###

# @name addNew
POST {{baseUrl}}/{{resourceName}}
Content-Type: application/json

{
    "categoryId": "bcc3b851-d704-4e44-9684-512910931e8a",
    "name": "Practical Concrete Pizza New",
    "color": "blue",
    "price": 322,
    "description": "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
    "thumbnailUrl": "http://placeimg.com/400/400"
}

###

# @name update
@idProduct=chTisEs
PATCH  {{baseUrl}}/{{resourceName}}/{{idProduct}}
Content-Type: application/json

{
  "name": "Practical Concrete Pizza Update",
  "color": "black",
  "price": 325
}

###

# @name remove
DELETE  {{baseUrl}}/{{resourceName}}/6
